version: "3.8"

services:
  postgre-example:
    image: postgres:16-alpine
    container_name: postgres-accounting
    ports:
      - protocol: tcp
        published: 5432
        target: 5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
